# Generated by Django 2.1.1 on 2018-09-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(default='3年级１班', max_length=18)),
                ('g_boy_num', models.IntegerField(default=0)),
                ('g_girl_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('s_age', models.IntegerField(default=18)),
                ('s_sex', models.BooleanField(default=0)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
